### ISSUE TITLE
can't run under fig

### ISSUE THREAD

**Issue by srobertson** [gliderlabs/docker-consul#35]
I realize that this maybe an issue with fig/boot2docker more than docker-consul. But thought I start here to collect info in order to open a bug report.

I can run docker consul just fine from boot2docker on the command line

```
$docker run -t -i  -p 8400:8400 -p 8500:8500 -p 8600:53/udp -name consul progrium/consul   -server  -bootstrap
```

However if I try to autumate running consul and registrator in a dev enviroment using fig and this file.

```
consul:
  ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"
  image: progrium/consul
  hostname: node1
  name: consul
  command: -server  -bootstrap

registrator:
  links:
    - consul:consul
  hostname: dev.6sense.com
  image: progrium/registrator
  command: consul://consul:8500 --ttl 500
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock

```

I get the following  errors 

```
consul_1      |     2014/11/09 02:08:04 [ERR] raft: Failed to make RequestVote RPC to 172.17.0.89:8300: dial tcp 172.17.0.89:8300: no route to host
consul_1      |     2014/11/09 02:08:04 [ERR] raft: Failed to make RequestVote RPC to 172.17.0.89:8300: dial tcp 172.17.0.89:8300: no route to host
consul_1      |     2014/11/09 02:08:04 [ERR] raft: Failed to make RequestVote RPC to 172.17.0.89:8300: dial tcp 172.17.0.89:8300: no route to host
consul_1      |     2014/11/09 02:08:05 [ERR] http: Request /v1/health/service/demanda?passing=1&tag=production&wait=60000ms, error: No cluster leader
consul_1      |     2014/11/09 02:08:05 [ERR] http: Request /v1/health/service/demanda?passing=1&tag=staging&wait=60000ms, error: No cluster leader
consul_1      |     2014/11/09 02:08:05 [ERR] http: Request /v1/health/service/dataapi?passing=1&tag=staging&wait=60000ms, error: No cluster leader
consul_1      |     2014/11/09 02:08:05 [ERR] http: Request /v1/health/service/ui?passing=1&tag=production&wait=60000ms, error: No cluster leader
consul_1      |     2014/11/09 02:08:05 [ERR] http: Request /v1/health/service/ui?passing=1&tag=staging&wait=60000ms, error: No cluster leader
consul_1      |     2014/11/09 02:08:05 [WARN] raft: Election timeout reached, restarting election
consul_1      |     2014/11/09 02:08:05 [INFO] raft: Node at 172.17.0.93:8300 [Candidate] entering Candidate state
consul_1      |     2014/11/09 02:08:07 [WARN] raft: Election timeout reached, restarting election
consul_1      |     2014/11/09 02:08:07 [INFO] raft: Node at 172.17.0.93:8300 [Candidate] entering Candidate state
consul_1      |     2014/11/09 02:08:07 [ERR] raft: Failed to make RequestVote RPC to 172.17.0.89:8300: dial tcp 172.17.0.89:8300: no route to host
consul_1      |     2014/11/09 02:08:07 [ERR] raft: Failed to make RequestVote RPC to 172.17.0.89:8300: dial tcp 172.17.0.89:8300: no route to host
consul_1      |     2014/11/09 02:08:08 [WARN] raft: Election timeout reached, restarting election
consul_1      |     2014/11/09 02:08:08 [INFO] raft: Node at 172.17.0.93:8300 [Candidate] entering Candidate state
consul_1      |     2014/11/09 02:08:09 [WARN] raft: Election timeout reached, restarting election
consul_1      |     2014/11/09 02:08:09 [INFO] raft: Node at 172.17.0.93:8300 [Candidate] entering Candidate state
```

Is this related to the ARP issue?
